apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:  
  selector:
    matchLabels:
        app: grpc-server
        component: grpc-server-app
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-server
        component: grpc-server-app
    spec:
      containers:
        - name: grpc-server-app
          image: jonhussnavitaire.azurecr.io/samples/grpcserver:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Test
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
    name: grpc-server
spec:
  ports:
    - name: http-port
      port: 80
      targetPort: 5001
  selector:
    app: grpc-server
  type: LoadBalancer