#if NETSTANDARD2_1
using System;
using ProtoBuf.Grpc.Client;
using Grpc.Net.Client;
using Grpc.Core;
using Microsoft.Extensions.Logging;

namespace BasicGrpcSample.ClientLib
{
    public class GrpcCoreClientFactory : IGrpcClientFactory, IDisposable
    {
        private readonly GrpcChannel _channel;

        public GrpcCoreClientFactory(string grpcServerAddress)
        {
            var opt = new GrpcChannelOptions()
            {
                Credentials = ChannelCredentials.Insecure
            };

            _channel = GrpcChannel.ForAddress(grpcServerAddress, opt);
        }

        public void Dispose()
        {
            _channel.Dispose();
        }

        public T GetClient<T>() where T : class
        {
            var isAutogenerated = typeof(T).IsSubclassOf(typeof(Grpc.Core.ClientBase));
            if (isAutogenerated)
            {
                return (T)Activator.CreateInstance(typeof(T), _channel);
            }

            var svc = _channel.CreateGrpcService<T>();
            return svc;
        }
    }
}
#endif
